# MIT License
#
# Copyright (c) [2019] [Angelo Ferrando]
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# Config file for the instrumentation of ROS
# this file is given in input to generator
#
nodes: # here we list the nodes we are going to monitor
  - node:
      name: talker
      package: beginner_tutorials
      path: /home/user/catkin_ws/src/beginner_tutorials/run.launch
  - node:
      name: listener
      package: beginner_tutorials
      path: /home/user/catkin_ws/src/beginner_tutorials/run.launch

monitors: # here we list the monitors we are going to generate
  - monitor:
      id: monitor_0
      log: home/user/catkin_ws/log.txt # file where the monitor will log the observed events
      silent: False # we let the monitor to print info during its execution
      warning: 1 #we let the monitor to publish error content through monitor_error topic otherwise (for warning:0), monitor_error does not publish anything.
      oracle: # the oracle running and ready to check the specification (localhost in this case)
        port: 8080 # the port where it is listening
        url: 127.0.0.1 # the url where it is listening
        action: nothing # the oracle will not change the message
      topics: # the list of topics this monitor is going to intercept
        - name: chatter # name of the topic
          type: std_msgs.msg.String # type of the topic
          action: filter #
          publishers:
            - talker
